version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=codemobiles
      - POSTGRES_PASSWORD=password
    volumes:
      - ./db_data:/var/lib/postgresql/data
  pgadmin4:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "1112:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=codemobiles@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=password
    volumes:
      - ./pgadmin:/var/lib/pgadmin
  web:
    image: odoo:15.0
    depends_on:
      - postgres
    ports:
      - "8069:8069"
    environment:
      - HOST=postgres
      - USER=codemobiles
      - PASSWORD=password
    volumes:
      - ./web_data:/var/lib/odoo
      # - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons

volumes:
  odoo-pgadmin-data:
    name: odoo-pgadmin
